name: Test Develop

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install MEOS
      run: |
        apt install build-essential cmake postgresql-server-dev-15 libproj-dev libjson-c-dev libgsl-dev libgeos-dev
        git clone --branch develop https://github.com/MobilityDB/MobilityDB
        mkdir MobilityDB/build
        cd MobilityDB/build
        cmake .. -DMEOS=on
        make -j
        make install
    - name: Install python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r pymeos_cffi/dev-requirements.txt
        pip install -r pymeos/dev-requirements.txt
    - name: Install pymeos_cffi
      run: |
        cd pymeos_cffi
        python ./pymeos_cffi/builder/build_header.py
        python ./pymeos_cffi/builder/build_pymeos_functions.py
        pip install .
        cd ..
    - name: Test PyMEOS with pytest
      run: |
        cd pymeos
        pytest
